openapi: 3.0.0
info:
  title: jaoapi
  version: '1.0'
  description: |-
    jao Minecraft Server API Version 1

    Old documentation: https://jaoafa.github.io/api-docs_old/

    ## Basic Infomation

    - BaseURL: `https://api.jaoafa.com/`
    - Available Version: `v1` (`https://api.jaoafa.com/v1/`)
    - バージョンを指定せずリクエストすることもできます。その場合、最新バージョンが選択されます。
    - GETリクエストにおいて、同一エンドポイントに対してのリクエストで同一フィールドを複数指定した場合、?で指定されたフィールドを優先して使用します。
      - `v1/users/X4Z?mcid=mine_book000`: mcid=`mine_book000`のデータを取得
      - `v1/users/X4Z?uuid=xxxxx`: uuid=`xxxxx`のデータを取得

    ## Rate Limits

    すべてのエンドポイントにおいて、リクエスト先エンドポイントに関係なく同一IPアドレスからの10秒以内に2回以上のリクエストを規制します。
    リクエストが規制された場合、レスポンスヘッダーのx-ratelimit-resetに制限が解除されるUNIXTimeが記載されます。

    `/club/token`で取得されたトークンを`usertoken`パラメーターに設定してリクエストした場合、トークンが有効であればレートリミット制限が無効化されます。
    また、Google reCAPTCHAでの認証トークンを`raterecaptcha`パラメーターに設定してリクエストした場合でも、トークンが有効であればレートリミット制限が無効化されます。

    ## Other Restriction

    開発部は開発部の判断により特定IPからのアクセスを禁止、またはレートリミットを無効化する処置を行うことができます。
  license:
    name: jaoLicense
    url: 'https://github.com/jaoafa/jao-Minecraft-Server/blob/master/jaoLICENSE.md'
  contact:
    url: 'https://jaoafa.com/contact'
    name: Contact
    email: info@jaoafa.com
  termsOfService: 'https://jaoafa.com/rule'
servers:
  - url: 'https://api.jaoafa.com/v1'
    description: API Server
components:
  schemas:
    User:
      title: User
      type: object
      x-examples: {}
      description: jao Minecraft Server Minecraft サービスにログインしたことのある利用者の情報オブジェクト
      properties:
        mcid:
          type: string
          example: X4Z
          pattern: '^[A-Za-z0-9_]+$'
          minLength: 3
          maxLength: 16
          description: Minecraft ID
        uuid:
          type: string
          format: uuid
          example: 5799296a-d1ec-4252-93bd-440bb9caa65c
          pattern: '^[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}$'
          minLength: 36
          maxLength: 36
          description: Minecraft UUID (with hyphen)
        discordid:
          type: string
          example: '206692134991036416'
          pattern: '^[0-9]+$'
          description: Discord ID
        permission:
          type: string
          enum:
            - Admin
            - Moderator
            - Regular
            - Verified
            - Default
          example: Admin
          description: Permission Group
        lastlogin:
          type: string
          example: '2020-04-12 09:03:58'
          description: Last login time
      required:
        - mcid
        - uuid
        - discordid
        - permission
        - lastlogin
  securitySchemes: {}
paths:
  '/users/{minecraft_id}':
    parameters:
      - schema:
          type: string
          example: X4Z
          pattern: '^[A-Za-z0-9_]+$'
          minLength: 3
          maxLength: 16
        name: minecraft_id
        in: path
        required: true
        description: Minecraft ID
    get:
      summary: GetUser
      tags:
        - Users
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  status:
                    type: boolean
                    description: Response status
                  code:
                    type: integer
                    example: 200
                    description: HTTP Status code
                  version:
                    type: string
                    minLength: 1
                    description: GitHub commit ID
                  data:
                    $ref: '#/components/schemas/User'
                required:
                  - status
                  - code
                  - version
                  - data
      operationId: get-users-minecraft.id
      description: |-
        ユーザオブジェクトを返します。
        このエンドポイントで返されるMinecraft IDは最新でない可能性があることに注意してください。jao Minecraft Serverの最終ログインの情報から取得されます。
      parameters: []
tags:
  - name: Users
security: []
